# Generated by Django 5.2.3 on 2025-06-23 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="estoque",
            field=models.IntegerField(default=0, verbose_name="Estoque Disponível"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="pontos_necessarios",
            field=models.IntegerField(verbose_name="Pontos Necessários"),
        ),
    ]
