# Generated by Django 5.2.3 on 2025-06-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_produto_atualizado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="observacao",
            field=models.TextField(
                blank=True,
                help_text="Observações adicionais sobre o cliente, como origem da criação.",
                null=True,
            ),
        ),
    ]
