# Generated by Django 5.2.3 on 2025-06-20 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(
                        max_length=200, verbose_name="Nome Completo do Cliente"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="Posto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Posto"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Endereço"
                    ),
                ),
            ],
            options={
                "verbose_name": "Posto",
                "verbose_name_plural": "Postos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Produto"),
                ),
                (
                    "pontos_necessarios",
                    models.PositiveIntegerField(verbose_name="Pontos Necessários"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Resgate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_resgate",
                    models.CharField(
                        default="Resgate em estabelecimentos escolhidos (estoque próprio)",
                        max_length=255,
                        verbose_name="Tipo de Resgate",
                    ),
                ),
                (
                    "gerado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Gerado Em"
                    ),
                ),
                ("vencimento", models.DateTimeField(verbose_name="Vencimento")),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GERADO", "Gerado"),
                            ("RESGATADO", "Resgatado"),
                            ("VENCIDO", "Vencido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="GERADO",
                        max_length=10,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "pontos_totais_resgatados",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="Total Resgatado (Pontos)"
                    ),
                ),
                (
                    "codigo_rastreamento",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Código de Rastreamento",
                    ),
                ),
                (
                    "nome_recebedor",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome do Recebedor (na entrega)",
                    ),
                ),
                (
                    "assinatura_recebedor",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Assinatura Recebedor (Base64/Imagem)",
                    ),
                ),
                (
                    "nome_motorista",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome do Motorista (na entrega)",
                    ),
                ),
                (
                    "assinatura_motorista",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Assinatura Motorista (Base64/Imagem)",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resgates",
                        to="core.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "posto_resgate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resgates",
                        to="core.posto",
                        verbose_name="Posto de Resgate",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resgates",
                        to="core.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resgate",
                "verbose_name_plural": "Resgates",
                "ordering": ["-gerado_em"],
            },
        ),
    ]
