# Generated by Django 5.2.3 on 2025-06-24 18:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_cliente_cpf"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioGerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        help_text="ID único de cada relatório gerado.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("GERAL", "Relatório Geral"),
                            ("MANIFESTO_LOTE", "Manifesto de Lote"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_geracao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("filtros_aplicados", models.JSONField(blank=True, null=True)),
                (
                    "codigo_rastreamento_lote",
                    models.CharField(
                        blank=True,
                        help_text="Código de rastreamento se for um manifesto de lote.",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Gerado",
                "verbose_name_plural": "Relatórios Gerados",
                "ordering": ["-data_geracao"],
            },
        ),
        migrations.AlterField(
            model_name="resgate",
            name="codigo_rastreamento",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=32,
                unique=True,
                verbose_name="Código de Rastreamento",
            ),
        ),
    ]
